2025-05-18 02:47:55 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-18 02:47:55 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-18 03:00:08 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-18 03:00:08 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 08:45:04 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 08:45:04 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 08:46:14 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 08:46:14 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 08:49:15 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 08:49:15 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 08:49:18 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 08:49:18 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 08:51:46 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 08:51:46 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 08:51:48 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 08:51:48 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 08:53:23 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\base.py changed, reloading.
2025-05-24 08:53:23 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\base.py changed, reloading.
2025-05-24 08:53:26 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 08:53:26 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:02:58 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 09:02:58 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 09:09:31 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:09:31 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:10:11 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:10:11 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:19:19 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 09:19:19 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 09:19:21 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:19:21 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:19:33 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:19:33 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:20:04 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:20:04 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:20:48 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 09:20:48 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 09:20:50 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:20:50 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:20:55 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 09:20:55 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:23:34 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:23:34 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:27:32 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 10:27:32 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 10:27:34 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:27:34 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:27:42 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 10:27:42 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 10:27:43 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:27:43 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:27:51 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:27:51 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:30:06 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 10:30:06 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 10:30:07 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:30:07 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:30:44 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:30:44 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:33:47 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 10:33:47 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 10:33:49 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:33:49 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:33:57 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 10:33:57 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 10:33:58 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 10:33:58 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 11:39:23 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 11:39:23 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 11:42:20 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 11:42:20 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 11:42:23 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 11:42:23 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 11:42:33 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 11:42:33 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\production.py changed, reloading.
2025-05-24 11:42:50 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 11:42:50 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 11:53:50 [ERROR   ] (log.log_response) Internal Server Error: /api/v2/rest_auth/chats/create/
Traceback (most recent call last):
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

2025-05-24 11:53:50 [ERROR   ] (log.log_response) Internal Server Error: /api/v2/rest_auth/chats/create/
Traceback (most recent call last):
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 244, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 503, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 420, in initial
    self.perform_authentication(request)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\views.py", line 330, in perform_authentication
    request.user
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\request.py", line 232, in user
    self._authenticate()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\request.py", line 385, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\rest_framework\authentication.py", line 127, in authenticate
    if not user or not user.is_active:
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\utils\functional.py", line 251, in inner
    self._setup()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\utils\functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\auth\middleware.py", line 39, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\auth\middleware.py", line 19, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\auth\__init__.py", line 304, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\auth\__init__.py", line 95, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 249, in _get_session
    self._session_cache = self.load()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 55, in load
    s = self._get_session_from_db()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 34, in _get_session_from_db
    return self.model.objects.get(
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\new_venv\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

2025-05-24 11:53:50 [ERROR   ] (basehttp.log_message) "POST /api/v2/rest_auth/chats/create/ HTTP/1.1" 500 145
2025-05-24 11:53:50 [ERROR   ] (basehttp.log_message) "POST /api/v2/rest_auth/chats/create/ HTTP/1.1" 500 145
2025-05-24 12:11:12 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\base.py changed, reloading.
2025-05-24 12:11:12 [INFO    ] (autoreload.trigger_reload) C:\Users\EMMANUEL CHIZARAM\Desktop\AbiaConnect\config\settings\base.py changed, reloading.
2025-05-24 12:11:14 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
2025-05-24 12:11:14 [INFO    ] (autoreload.run_with_reloader) Watching for file changes with StatReloader
